#!/bin/bash

echo "=== 크로스 플랫폼 뱀 게임 데모 ==="
echo ""
echo "🎮 게임 기능 체크리스트:"
echo ""
echo "✅ 1. 메인 메뉴 표시"
echo "✅ 2. 설정 메뉴 접근 및 설정 변경"
echo "✅ 3. 싱글플레이어 게임 시작"
echo "✅ 4. 실시간 점수/등급/통계 표시"
echo "✅ 5. 장애물 자동 생성 (사과 먹을 때마다 30% 확률)"
echo "✅ 6. 화면 깜빡거림 방지"
echo "✅ 7. 게임 오버 시 상세 통계 표시"
echo "✅ 8. 멀티플레이어 및 AI 배틀 모드"
echo "✅ 9. 크로스플랫폼 오디오 시스템"
echo "✅ 10. 실시간 사운드/음악 제어"
echo ""

echo "🎯 게임 플레이 가이드:"
echo "- 메인 메뉴: 화살표 키로 이동, Enter로 선택"
echo "- 설정: Settings에서 게임 속도, 격자, 사운드 설정 가능"
echo "- 게임 중: 화살표 키 또는 WASD로 조작, ESC로 메뉴 복귀"
echo "- 오디오: 설정 메뉴에서 사운드/음악 켜기/끄기 가능"
echo "- 점수 시스템:"
echo "  * 사과(@@) 먹기: +100점"
echo "  * 이동: +1점"
echo "  * 장애물(XX) 피하기 필수!"
echo ""
echo "🏆 등급 시스템:"
echo "  * Newbie: 0-199점"
echo "  * Beginner: 200-499점"  
echo "  * Amateur: 500-999점"
echo "  * Pro: 1000-1999점"
echo "  * Expert: 2000-4999점"
echo "  * Master: 5000-9999점"
echo "  * Legend: 10000점+"
echo ""
echo "🎵 오디오 시스템:"
echo "  * 메뉴 음악: 메인 메뉴 및 설정에서 재생"
echo "  * 게임 음악: 게임 플레이 중 배경음악"
echo "  * 효과음: 사과 먹기, 충돌, 레벨업, 메뉴 조작"
echo "  * 게임 오버 음악: 게임 종료 시 재생"
echo "  * 실시간 제어: 설정에서 즉시 켜기/끄기 가능"
echo ""

echo "게임을 시작하려면 Enter를 누르세요..."
read -r

echo "게임 시작 중..."
./build/snake

echo ""
echo "게임을 종료했습니다. 즐거우셨나요? 🐍"
